config/routes.rb
Rails.application.routes.draw do

  # Routes in development / testing
  if Rails.env == 'development' || Rails.env == 'test'
    # Set root of application
    root 'static_pages#home'

    # Static pages routes
    get '/home',            to: 'static_pages#home'
    get '/about',           to: 'static_pages#about'
    get '/resources',       to: 'static_pages#resources'
    get '/stories',         to: 'static_pages#stories'
    get '/public_speaking', to: 'static_pages#public_speaking'
    get '/policies',        to: 'static_pages#policies'
    get '/community/*subpath',       to: 'static_pages#community'
    get '/community',       to: 'static_pages#community'

    # Session routes
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    # Users API
    get '/signup', to: 'users#new' # Nicer route name than /users/new
    resources :users

    # Courses API
    get '/courses', to: 'courses#index'
    post '/courses', to: 'courses#create'
    get '/courses/new', to: 'courses#new'
    get '/courses/:course_id', to: 'courses#show'  # Should go last as it also catches most of the other routes
    put '/courses/:course_id', to: 'courses#update' # ^^^^
    delete '/courses/:course_id', to: 'courses#delete' # ^^^^
    get '/courses/:course_id/edit', to: 'courses#edit'  # ^^^^

    # Attachments API
    get '/courses/(:course_id)/attachments', to: 'courses#attachment_index'
    post '/courses/(:course_id)/attachments', to: 'courses#attachment_create'
    get '/courses/(:course_id)/attachments/documents/(:attach_id)', to: 'courses#attachment_get', defaults: { type: 'Document' }
    get '/courses/(:course_id)/attachments/embeds/(:attach_id)', to: 'courses#attachment_get', defaults: { type: 'Embed' }
    put '/courses/(:course_id)/attachments/(:attach_id)', to: 'courses#attachment_edit'
    delete "/courses/(:course_id)/attachments/documents/(:attach_id)", to: 'courses#attachment_delete', defaults: { type: 'Document' }
    delete "/courses/(:course_id)/attachments/embeds/(:attach_id)", to: 'courses#attachment_delete', defaults: { type: 'Embed' }

    get "/authorize/:user_id", to: "users#authorize"
    
  # Staged routes
  elsif Rails.env == 'stage'
    # Set root of application
    root 'static_pages#home'

    # Static pages routes
    get '/home',            to: 'static_pages#home'
    get '/about',           to: 'static_pages#about'
    get '/resources',       to: 'static_pages#resources'
    get '/stories',         to: 'static_pages#stories'
    get '/public_speaking', to: 'static_pages#public_speaking'
    get '/policies',        to: 'static_pages#policies'
    get '/community/*subpath',       to: 'static_pages#community'
    get '/community',       to: 'static_pages#community'

    # Session routes
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    # Users API
    get '/signup', to: 'users#new' # Nicer route name than /users/new
    resources :users

    # Courses API
    get '/courses', to: 'courses#index'
    post '/courses', to: 'courses#create'
    get '/courses/new', to: 'courses#new'
    get '/courses/:course_id', to: 'courses#show'  # Should go last as it also catches most of the other routes
    put '/courses/:course_id', to: 'courses#update' # ^^^^
    delete '/courses/:course_id', to: 'courses#delete' # ^^^^
    get '/courses/:course_id/edit', to: 'courses#edit'  # ^^^^

    # Attachments API
    get '/courses/(:course_id)/attachments', to: 'courses#attachment_index'
    post '/courses/(:course_id)/attachments', to: 'courses#attachment_create'
    get '/courses/(:course_id)/attachments/documents/(:attach_id)', to: 'courses#attachment_get', defaults: { type: 'Document' }
    get '/courses/(:course_id)/attachments/embeds/(:attach_id)', to: 'courses#attachment_get', defaults: { type: 'Embed' }
    put '/courses/(:course_id)/attachments/(:attach_id)', to: 'courses#attachment_edit'
    delete "/courses/(:course_id)/attachments/documents/(:attach_id)", to: 'courses#attachment_delete', defaults: { type: 'Document' }
    delete "/courses/(:course_id)/attachments/embeds/(:attach_id)", to: 'courses#attachment_delete', defaults: { type: 'Embed' }

    get "/authorize/:user_id", to: "users#authorize"
  # Released routes
  elsif Rails.env == 'production'
    # Set root of application
    root 'static_pages#home'

    # Static pages routes
    get '/home',            to: 'static_pages#home'
    get '/about',           to: 'static_pages#about'
    get '/resources',       to: 'static_pages#resources'
    get '/stories',         to: 'static_pages#stories'
    get '/public_speaking', to: 'static_pages#public_speaking'
    get '/policies',        to: 'static_pages#policies'
    get '/community/*subpath',       to: 'static_pages#community'
    get '/community',       to: 'static_pages#community'

    # Session routes
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    # Users API
    get '/signup', to: 'users#new' # Nicer route name than /users/new
    resources :users

    # Courses API
    get '/courses', to: 'courses#index'
    post '/courses', to: 'courses#create'
    get '/courses/new', to: 'courses#new'
    get '/courses/:course_id', to: 'courses#show'  # Should go last as it also catches most of the other routes
    put '/courses/:course_id', to: 'courses#update' # ^^^^
    delete '/courses/:course_id', to: 'courses#delete' # ^^^^
    get '/courses/:course_id/edit', to: 'courses#edit'  # ^^^^

    # Attachments API
    get '/courses/(:course_id)/attachments', to: 'courses#attachment_index'
    post '/courses/(:course_id)/attachments', to: 'courses#attachment_create'
    get '/courses/(:course_id)/attachments/documents/(:attach_id)', to: 'courses#attachment_get', defaults: { type: 'Document' }
    get '/courses/(:course_id)/attachments/embeds/(:attach_id)', to: 'courses#attachment_get', defaults: { type: 'Embed' }
    put '/courses/(:course_id)/attachments/(:attach_id)', to: 'courses#attachment_edit'
    delete "/courses/(:course_id)/attachments/documents/(:attach_id)", to: 'courses#attachment_delete', defaults: { type: 'Document' }
    delete "/courses/(:course_id)/attachments/embeds/(:attach_id)", to: 'courses#attachment_delete', defaults: { type: 'Embed' }

    get "/authorize/:user_id", to: "users#authorize"
  end

  resources :resources

  # Catch-all route
  get '*path', to: 'static_pages#coming_soon'
end

app/models/user.rb
class User < ApplicationRecord
	before_save { email.downcase! }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 6, maximum: 255}, 
    				allow_nil: true
	has_secure_password

  	has_many :enrollments, dependent: :destroy
	has_many :courses, through: :enrollments
	has_many :resources, dependent: :destroy

	# Returns the hash digest of the given string.
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	                                              BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# Given an auth hash from third party API,
	# either log the given user in if they exist, or create new user
	# with given info
	def self.find_or_create_from_auth_hash(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
			# Create new user if couldn't find them
			password = SecureRandom.urlsafe_base64
			user.provider = auth.provider
			user.uid = auth.uid
			user.name = auth.info.first_name + auth.info.last_name
			user.email = auth.info.email
			user.password = password
			user.password_confirmation = password
			user.save!
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_member?, only: [:edit, :update, :destroy]

  def authorize
    user = User.find(params[:user_id]) || current_user
    if user && user.role == Role.admin || user.role == Role.moderator
      render status: 200, json: { result: 'authorized' }
    else
      render status: 401, json: { result: 'unauthorized' }
    end
  end

  def index
    # temporarily redirect
    return redirect_to '/'

  	@users = User.all.order(:created_at)
  end

  def preview_profile
    # temporarily redirect
    return redirect_to '/'
  end

  def show 
    # temporarily redirect
    return redirect_to '/'
  	@user = User.find(params[:id])
  end

  def new 
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in(@user)
  		flash[:success] = "Account created!"
      # redirect_to @user
      redirect_to "/"
  	else 
  		render 'new'
  	end
  end

  def edit 
    # temporarily redirect
    return redirect_to '/'
    @user = User.find(params[:id])
  end

  def update 
    # temporarily redirect
    return redirect_to '/'
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    # temporarily redirect
    return redirect_to '/'
    User.find(params[:id]).destroy
    flash[:success] = "Profile Updated Successfully."
    redirect_to root_url
  end



  private 
  	def user_params
  		params.require(:user).permit(:username, :name, :email, :password, 
  									:password_confirmation)
  	end

end

app/views/users/_user.html.erb
User: <%= user.name %> <br>

app/views/users/_user_profile.html.erb
placeholder for user profile

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>
<div class='container text-center'>
	<h3>User Edit</h3>
	<p><%= link_to "Delete my account", user_path(user), method: destroy %></p>

	<div class="row">
	  <div class="col-md-6 col-md-offset-3">
	    <%= form_for(@user) do |f| %>
	      <%= render 'shared/error_messages', object: @user %>
	      <%= f.label :name %>
	      <%= f.text_field :name, class: 'form-control' %>

	      <%= f.label :username %>
	      <%= f.text_field :username, class: 'form-control' %>

	      <%= f.label :email %>
	      <%= f.email_field :email, class: 'form-control' %>

	      <%= f.label :password %>
	      <%= f.password_field :password, class: 'form-control' %>

	      <%= f.label :password_confirmation, "Confirmation" %>
	      <%= f.password_field :password_confirmation, class: 'form-control' %>

	      <%= f.submit "Edit my account", class: "btn btn-primary" %>
	    <% end %>
	  </div>
	</div>

</div>

app/views/users/index.html.erb
<% provide(:title, "Users") %>

<div class='container'>
	<h2>Users Index Page!</h2>
	<%= render @users %>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<%= stylesheet_link_tag 'pages/login', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="banner-sm" style="background-image: url(<%= asset_path('backgrounds/anton-darius-thesollers-271293-unsplash.jpg') %>)">
  <div class="row d-flex align-items-center">
    <div class="message text-center d-lg-none col-sm-12">
      <p class="light-text title serif clear-theme">New Account</p>
    </div>
    <div class="message text-center col-lg-6 col-sm-12">
      <p class="light-text title sans-serif clear-theme">

        <div class="shadow-box">
					<%= form_for(@user) do |f| %>
						<%= render 'shared/error_messages', object: @user %>

						<%= f.text_field :name, class: 'form-control input', placeholder: "Name" %>

						<%= f.text_field :username, class: 'form-control input', placeholder: "Username" %>

						<%= f.email_field :email, class: 'form-control input', placeholder: "Email" %>

						<%= f.password_field :password, class: 'form-control input', placeholder: "Password" %>

						<%= f.password_field :password_confirmation, class: 'form-control input', placeholder: "Confirm Password"  %>

						<%= f.submit "Create my account", class: "btn button border clear-theme clear-hover" %>
					<% end %>
        </div>

        <div class="shadow-box">
          Already have an account?
          <%= link_to "/login" do %>
            <button class="button">Log in here!</button>
          <% end %>
        </div>

      </p>
    </div>
    <div class="message text-center d-sm-none d-lg-block col-lg-6">
      <p class="light-text title serif clear-theme">New Account</p>
    </div>
  </div>
</div>

app/views/users/preview_profile.html.erb
<%= render "users/user_profile" %>

app/views/users/show.html.erb
<% provide(:title, "#{@user.name}") %>

<div class='container'>
	<h4><%= @user.name %> </h4>
	<% if @user == current_user %>
		<%= link_to "Sign out", logout_path, method: 'delete' %>
	<% end %>

</div>
	